Add docs for highlights, notes, archive, unarchive, and calculate ratings endpoints
rayyansys/rayyan-api-docs pull request #13
Opened 2023-02-02 19:45 UTC by maboelnour

This PR adds docs for these endpoints:
- DELETE `reviews/:review_id/highlight`
- POST `reviews/:review_id/highlights`
- DELETE `reviews/:review_id/articles/:article_id/notes/:note_id`
- PUT `reviews/:review_id/articles/:article_id/notes/:note_id`
- POST `reviews/:review_id/articles/:article_id/notes`
- POST `reviews/:review_id/archive`
- POST `reviews/:review_id/unarchive`
- POST `reviews/:review_id/calculate_ratings`

2023-02-03 02:20 UTC, hammady requested changes
No text provided in the "Docs" section for each endpoint.

2023-02-05 16:27 UTC, maboelnour commented
@hammady I added info in the `Docs` section for each request.

2023-02-06 18:28 UTC, hammady requested changes

2023-02-06 18:28 UTC, hammady commented on .insomnia/Request/req_26bf11ada1a445d595472cc0dfc8a61f.yml
> +description: This endpoint archive the review
```suggestion
description: This endpoint archives the review
```

2023-02-06 18:28 UTC, hammady commented on .insomnia/Request/req_fa38417da7fb46ddaa3f35859090e066.yml
> +description: This endpoint unarchive the review
```suggestion
description: This endpoint unarchives the review
```

2023-02-06 18:29 UTC, hammady approved these changes

2023-02-07 19:09 UTC, merged