Add mendeley docs
rayyansys/rayyan-api-docs pull request #16
Opened 2023-03-18 21:41 UTC by maboelnour

Add docs for:
`GET /api/v1/third_party_auth/mendeley`
`GET /api/v1/third_party_auth/mendeley_access_token`
`GET /api/v1/third_party_auth/mendeley_access_token_from_code`

2023-03-20 01:38 UTC, hammady requested changes
It is not clear what API clients should do to run to authorize Mendeley. It should mention that they should do request X in a new window or in-app browser and watch for the onload event and status code, ... etc.

2023-03-21 23:34 UTC, maboelnour commented
> It is not clear what API clients should do to authorize Mendeley. It should mention that they should do request X in a new window or in-app browser and watch for the onload event and status code, ... etc.

After our discussion, we agreed to document the process in the `Fetch mendeley auth link` endpoint.

Done.

2023-03-23 03:03 UTC, hammady requested changes

2023-03-26 17:39 UTC, maboelnour commented on .insomnia/Request/req_69905de944434b278dc6e574cceaec72.yml
> +  - If you got `204 Created`  it's means that an access token has already generated and no need to capture the `code` and no need to call `Generate access token from code` endpoint, instead you shoul
Fixed.

2023-03-27 21:00 UTC, hammady approved these changes

2023-04-03 15:23 UTC, merged